create table if not exists public.events (
  id bigint generated by default as identity primary key,
  event_name text not null,
  session_id text,
  scenario text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  session_id text,
  scenario text,
  rating integer not null check (rating between 1 and 5),
  would_practice_again text not null check (would_practice_again in ('Yes','Maybe','No')),
  comment text,
  created_at timestamptz not null default now()
);

alter table public.events enable row level security;
alter table public.feedback enable row level security;

-- No public policies are required because inserts/reads are performed by
-- Vercel serverless functions using SUPABASE_SERVICE_ROLE_KEY.
